version: '3'

services:

  node1:
    container_name: node1
    image: golang:1.14.3
    volumes:
      - ./build:/go/bin
      - ./docker/config:/root/config
      - ./docker/scripts:/root/scripts
    working_dir: /root/scripts
    command: "bash genesis.sh node1"
    ports:
    - 127.0.0.1:26656:26656
    - 127.0.0.1:26657:26657
    - 127.0.0.1:1317:1317

  node2:
    container_name: node2
    image: golang:1.14.3
    volumes:
      - ./build:/go/bin
      - ./docker/config:/root/config
      - ./docker/scripts:/root/scripts
    working_dir: /root/scripts
    command: bash -c "sleep 10; bash /root/scripts/addNode.sh node2"
    depends_on:
      - node1
