version: '3'

services:
  x-default: &default
    image: golang:1.14.3
    volumes:
      - ./build:/go/bin
      - ./docker/config:/root/config
      - ./docker/scripts:/root/scripts
    working_dir: /root/scripts

  node2:
    container_name: node2
    <<: *default
    command: bash -c "sleep 10; bash /root/scripts/addNode.sh node2"


  node3:
    container_name: node3
    <<: *default
    command: bash -c "sleep 10; bash /root/scripts/addNode.sh node3"


  node4:
    container_name: node4
    <<: *default
    command: bash -c "sleep 10; bash /root/scripts/addNode.sh node4"


  node5:
    container_name: node5
    <<: *default
    command: bash -c "sleep 10; bash /root/scripts/addNode.sh node5"

