name: Linting

on:
  - pull_request

jobs:
  lint:
    strategy:
      matrix:
        go-version:
          - 1.15.x
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CICD_RSA_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_GITHUB }}
          
      - name: Git config
        run: |
          git config --global url."git@github.com:axelarnetwork".insteadOf https://github.com/axelarnetwork

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
          only-new-issues: true
